### ISSUE TITLE
Footnotes in explanations should unfold

### ISSUE THREAD

**Issue by NSkelsey** [ldemarest/ombuds-home#4]
The footnotes must be well written, explanatory and hidden from the user, unless the appropriate word is clicked.

**Comment by ldemarest** [comment]
first iteration complete

**Comment by NSkelsey** [comment]
Dependent unfolding bits of text should hide if the parent unfolded para that unfolded them hides.

You could just disable the toggle that hides the text to fix this. Its not very intuitive to click again on the word to hide its corresponding unfolded text.

Notice that the **2 footnote** has been hid in the example below:
![screen shot 2016-02-01 at 4 23 04 pm](https://cloud.githubusercontent.com/assets/1095794/12731714/2b4fbf9c-c900-11e5-8646-14b29a6da56f.png)

**Comment by ldemarest** [comment]
I agree, toggle disabled for now.

**Comment by NSkelsey** [comment]
Dropping footnote 4 closes this issue. It also drops an easter egg. `¯\_(ツ)_/¯`

**Comment by ldemarest** [comment]
Disabled unfolding to have default visibility of footnotes. I think this creates a better visual flow and relies less on user interaction. Perhaps make font size variation between standard text and footnote text.
